name: Create Release Pull Request
on: [workflow_dispatch]

jobs:
  create_release_pull_request:
    name: Create Release Pull Request
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Fetch version
        id: details
        run: |
          echo ::set-output name=version::$(node -p "require('./package.json').version")

      - name: Get Release Details
        id: release_details
        uses: botpress/gh-actions/get_release_details@v2

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.BOTPRESS_BOT_APP_ID }}
          private_key: ${{ secrets.BOTPRESS_BOT_APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          title: 'chore(server): release v${{ steps.details.outputs.version }}'
          commit-message: 'chore(server): release v${{ steps.details.outputs.version }}'
          branch: 'release/v${{ steps.details.outputs.version }}'
          body: ${{ steps.release_details.outputs.changelog }}
