name: Publish Documentation
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
jobs:
  publish:
    name: Publish Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.13.0'
      - name: Install python3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install Tools
        run: |
          pip install awscli
      - name: Build docs
        run: |
          yarn
          yarn cmd build:guide
          cp docs/guide/website/build/botpress-docs/index.html docs/guide/website/build/botpress-docs/docs/index.html
      - name: Publish docs
        env:
          DOCS_BUCKET_NAME: ${{ secrets.DOCS_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync docs/guide/website/build/botpress-docs s3://$DOCS_BUCKET_NAME/ --delete
